# This is a basic workflow to help you get started with Actions

name: Build and Package

env:
  LIBRARY_FOLDER: ./src/packagetemplate

on:
  push:
    tags:
      - "release/*"

jobs:
  build:
    runs-on: windows-latest

    steps:      
      - name: Get Version 
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\/release\//}
        shell: bash
      
      - name: checkout
        uses: actions/checkout@v2
        
      - name: Setup NuGet.exe for use with actions
        uses: NuGet/setup-nuget@v1.0.2        
        
      - name: setup .net core
        uses: actions/setup-dotnet@v1.4.0
      
      - name: install umbpack
        run: dotnet tool install Umbraco.Tools.Packages --global
        
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1
      
      - name: build
        run: msbuild ./src -p:Configuration=Release
      
      - name: nuget 
        run: nuget pack ${{ env.LIBRARY_FOLDER }} -version ${{ steps.get_version.outputs.VERSION }} -OutputDirectiory .\out
        
      - name: upload-artifact
        uses: actions/upload-artifact@v2
        with:
          name: BuildResults
          path: ./out/**/*
